name: debug

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    debug:
        name: Check Types
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Print Environment Variables
              run: |
                echo "Environment Variables:"
                printenv
