name: Dry Run (Release)
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Bun Runtime
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Test
              run: bun test
              continue-on-error: false
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Bun Runtime
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Check types
              run: bun run check-types
              continue-on-error: false
            - name: Build
              run: bun run build 
              env:
                NODE_ENV: production
                WAAVY_CLI_COMMAND_INCLUDE_BUNDLE: ${{ secrets.WAAVY_CLI_COMMAND_INCLUDE_BUNDLE }}
                WAAVY_CLI_COMMAND_INCLUDE_CREATE: ${{ secrets.WAAVY_CLI_COMMAND_INCLUDE_CREATE }}
                WAAVY_CLI_COMMAND_INCLUDE_PRERENDER: ${{ secrets.WAAVY_CLI_COMMAND_INCLUDE_PRERENDER }}
                WAAVY_CLI_COMMAND_INCLUDE_RENDER: ${{ secrets.WAAVY_CLI_COMMAND_INCLUDE_RENDER }}
                WAAVY_CLI_COMMAND_INCLUDE_SSG: ${{ secrets.WAAVY_CLI_COMMAND_INCLUDE_SSG }}
                WAAVY_CLI_COMMAND_INCLUDE_UPGRADE: ${{ secrets.WAAVY_CLI_COMMAND_INCLUDE_UPGRADE }}
            